### PR TITLE
connect the search input to the qs

### PR DESCRIPTION
**Pull request by GuyAvraham**
https://trello.com/c/wimragDZ

### CODE REVIEW

**Comment by rootux** [comment]
@GuyAvraham Apparently the debounce this really slows down search.
Try to replace the debounced in the `serach-bar.js` to 2000 vs. 5 and you'll see what I mean.
Why do we need the debounce there?

**Comment by rootux** [comment]
OK. Actually cancelling it if I type fast enough it gets overwritten which is not a good UX. Is there another way to solve this - cause that number 50 feels a bit slow in terms of ux

**Comment by rootux** [comment]
Actually scratch the last - I've tried with different numbers and it still gave me the same. It might not be connected.

**Comment by rootux** [comment]
Could be a separate bug - Try to enter text fast into the search field. I guess right now it's sync which kind of gets the UI thread stuck - @GuyAvraham Can you check that please?

**Comment by GuyAvraham** [comment]
yes I will check it today. can I see it on staging now? or is there another dev env that I dont know of

**Comment by rootux** [comment]
Once I push to staging you should see it in staging. I'll do that now.
I believe it's already pushed there actually. so yes.
https://staging.doocrate.com

**Pull request merged**
