### PR TITLE
adding prettier through eslint

### PR DESCRIPTION
**Pull request by GuyAvraham**

### CODE REVIEW

**Comment by rootux** [comment]
Interesting.
Another cool project I saw uses prettier on an on-commit git hook - 
https://github.com/withspectrum/spectrum#contributing

"We run Prettier on-commit, which means you can write code in whatever style you want and it will be automatically formatted according to the common style when you run git commit. We also have ESLint setup, although we've disabled all stylistic rules since Prettier takes care of those."

**Comment by GuyAvraham** [comment]
cool, Will check it
------

Do you plan to use this platform
https://spectrum.chat/

Instead of the facebook group?
Do they allow task management?
What is missing in trello that doocrate offers?

**Comment by GuyAvraham** [comment]
Do you plan to use this platform
https://spectrum.chat/
1. Instead of the facebook group? 
2. Do they allow task management?
3. What is missing in trello that doocrate offers?

**Comment by GuyAvraham** [comment]
@rootux 
I can add
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged"
    }
  }
into package.json and it will auto ident on each commit.
my only problem is here: browserUtil.js . getUrlSearchParams, the last return
originally its:
`return (q[key] = value, q)`
but for some reason prettier is changing it to be 
`return (q[key] = value), q;`

any idea?

**Pull request closed without merging**
