### PR TITLE
[WIP] Audit log

### PR DESCRIPTION
**Pull request by nimast**
# 🚧  NOT READY TO MERGE 🚧  
This PR contains code which creates an 'audit' collection in firestore and stores a snapshot of a record in it for every task creation, update or delete. The data model is capable of handling other entity types as well.
I'm posting it here to get some comments, I was thinking not everybody might want a snapshot on each update? we can also make it configurable . 
Would appreciate your feedback 😊

### CODE REVIEW

**Comment by rootux** [comment]
@nimast So the idea is to have an history of all the actions happens to tasks?
Like someone Created a task, modified it - Sound like a great idea!

**Comment by nimast** [comment]
Cool! Its even working. The only concern is the number of updates, right now we perform an update on every field change (like we should), so this can create a lot of update records. It's not such a big deal but I wanted to discuss. We will go to production with it tomorrow so we can also wait a bit for the change to be battle tested ;) check us out: tasks.xoshen.art

**Comment by rootux** [comment]
That looks amazing.
I would remove the initial redirect to this url - '?filter=taskType&text=2'
And generally would remove all the filters.
Also - set up the email client so you could communicate through emails.
Add people to `/admins` or `/guides` to allow more control :)
Looks great! Tell me if you need any support!

**Comment by rootux** [comment]
Closing due to old activity. Thank you.

**Pull request closed without merging**
