### PR TITLE
Improve User-info Modal (UI)

### PR DESCRIPTION
**Pull request by netanelben**
- Improve UI for both langs.
- Add email validation
- Improve logic and code readability 
- Remove redundant style

## UI Changed
|Before|After|
|--|--|
| Screen Shot 2019-10-09 at 0 38 00 | Screen Shot 2019-10-11 at 11 01 46 |

|EN|HE|
|--|--|
| Screen Shot 2019-10-11 at 11 01 58 | Screen Shot 2019-10-11 at 11 30 23 |

### CODE REVIEW

**Comment by netanelben** [comment]
Screen Shot 2019-10-11 at 14 01 13

@rootux 
I see UI changes are made and looks good !! 
so my UI changes seems redundant here..

maybe ill extract some of the JS code from here to a new PR..?

**Comment by rootux** [comment]
@netanelben yeah it seems to bother us both at the same time.
Please do so - your JS code is needed for the refreshment of this project :) Let's go with a new pr

**Review by rootux — CHANGES_REQUESTED** [review]
As agreed. waiting for the new pull request 🚀 🎸

**Comment by rootux** [comment]
Closing for now. As we merged this on a different branch

**Pull request closed without merging**
